services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "${UI_PORT-81}:81"
    environment:
      TZ: "${TZ:-Europe/Kyiv}"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy_net
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:81/"]
      interval: 30s
      timeout: 5s
      retries: 10

networks:
  proxy_net:
    external: true